use betcha_development;
insert into ranks (season,wk,rank,team_id) values(2007,1,1,(select team_id from teams where school_nm='USC' or abbreviation='USC'));
insert into ranks (season,wk,rank,team_id) values(2007,1,2,(select team_id from teams where school_nm='LSU' or abbreviation='LSU'));
insert into ranks (season,wk,rank,team_id) values(2007,1,3,(select team_id from teams where school_nm='West Virginia' or abbreviation='West Virginia'));
insert into ranks (season,wk,rank,team_id) values(2007,1,4,(select team_id from teams where school_nm='Texas' or abbreviation='Texas'));
insert into ranks (season,wk,rank,team_id) values(2007,1,5,(select team_id from teams where school_nm='Michigan' or abbreviation='Michigan'));
insert into ranks (season,wk,rank,team_id) values(2007,1,6,(select team_id from teams where school_nm='Florida' or abbreviation='Florida'));
insert into ranks (season,wk,rank,team_id) values(2007,1,7,(select team_id from teams where school_nm='Wisconsin' or abbreviation='Wisconsin'));
insert into ranks (season,wk,rank,team_id) values(2007,1,8,(select team_id from teams where school_nm='Oklahoma' or abbreviation='Oklahoma'));
insert into ranks (season,wk,rank,team_id) values(2007,1,9,(select team_id from teams where school_nm='Virginia Tech' or abbreviation='Virginia Tech'));
insert into ranks (season,wk,rank,team_id) values(2007,1,10,(select team_id from teams where school_nm='Louisville' or abbreviation='Louisville'));
insert into ranks (season,wk,rank,team_id) values(2007,1,11,(select team_id from teams where school_nm='Ohio State' or abbreviation='Ohio State'));
insert into ranks (season,wk,rank,team_id) values(2007,1,12,(select team_id from teams where school_nm='California' or abbreviation='California'));
insert into ranks (season,wk,rank,team_id) values(2007,1,13,(select team_id from teams where school_nm='Georgia' or abbreviation='Georgia'));
insert into ranks (season,wk,rank,team_id) values(2007,1,14,(select team_id from teams where school_nm='UCLA' or abbreviation='UCLA'));
insert into ranks (season,wk,rank,team_id) values(2007,1,15,(select team_id from teams where school_nm='Tennessee' or abbreviation='Tennessee'));
insert into ranks (season,wk,rank,team_id) values(2007,1,16,(select team_id from teams where school_nm='Rutgers' or abbreviation='Rutgers'));
insert into ranks (season,wk,rank,team_id) values(2007,1,17,(select team_id from teams where school_nm='Penn State' or abbreviation='Penn State'));
insert into ranks (season,wk,rank,team_id) values(2007,1,18,(select team_id from teams where school_nm='Auburn' or abbreviation='Auburn'));
insert into ranks (season,wk,rank,team_id) values(2007,1,19,(select team_id from teams where school_nm='Florida State' or abbreviation='Florida State'));
insert into ranks (season,wk,rank,team_id) values(2007,1,20,(select team_id from teams where school_nm='Nebraska' or abbreviation='Nebraska'));
insert into ranks (season,wk,rank,team_id) values(2007,1,21,(select team_id from teams where school_nm='Arkansas' or abbreviation='Arkansas'));
insert into ranks (season,wk,rank,team_id) values(2007,1,22,(select team_id from teams where school_nm='TCU' or abbreviation='TCU'));
insert into ranks (season,wk,rank,team_id) values(2007,1,23,(select team_id from teams where school_nm='Hawaii' or abbreviation='Hawaii'));
insert into ranks (season,wk,rank,team_id) values(2007,1,24,(select team_id from teams where school_nm='Boise State' or abbreviation='Boise State'));
insert into ranks (season,wk,rank,team_id) values(2007,1,25,(select team_id from teams where school_nm='Texas A&M' or abbreviation='Texas A&M'));