use betcha_development;
insert into ranks (season,wk,rank,team_id) values(2007,2,1,(select team_id from teams where school_nm='USC' or abbreviation='USC'));
insert into ranks (season,wk,rank,team_id) values(2007,2,2,(select team_id from teams where school_nm='LSU' or abbreviation='LSU'));
insert into ranks (season,wk,rank,team_id) values(2007,2,3,(select team_id from teams where school_nm='West Virginia' or abbreviation='West Virginia'));
insert into ranks (season,wk,rank,team_id) values(2007,2,4,(select team_id from teams where school_nm='Florida' or abbreviation='Florida'));
insert into ranks (season,wk,rank,team_id) values(2007,2,5,(select team_id from teams where school_nm='Wisconsin' or abbreviation='Wisconsin'));
insert into ranks (season,wk,rank,team_id) values(2007,2,6,(select team_id from teams where school_nm='Oklahoma' or abbreviation='Oklahoma'));
insert into ranks (season,wk,rank,team_id) values(2007,2,7,(select team_id from teams where school_nm='Texas' or abbreviation='Texas'));
insert into ranks (season,wk,rank,team_id) values(2007,2,8,(select team_id from teams where school_nm='Louisville' or abbreviation='Louisville'));
insert into ranks (season,wk,rank,team_id) values(2007,2,9,(select team_id from teams where school_nm='Virginia Tech' or abbreviation='Virginia Tech'));
insert into ranks (season,wk,rank,team_id) values(2007,2,10,(select team_id from teams where school_nm='California' or abbreviation='California'));
insert into ranks (season,wk,rank,team_id) values(2007,2,11,(select team_id from teams where school_nm='Georgia' or abbreviation='Georgia'));
insert into ranks (season,wk,rank,team_id) values(2007,2,12,(select team_id from teams where school_nm='Ohio State' or abbreviation='Ohio State'));
insert into ranks (season,wk,rank,team_id) values(2007,2,13,(select team_id from teams where school_nm='UCLA' or abbreviation='UCLA'));
insert into ranks (season,wk,rank,team_id) values(2007,2,14,(select team_id from teams where school_nm='Penn State' or abbreviation='Penn State'));
insert into ranks (season,wk,rank,team_id) values(2007,2,15,(select team_id from teams where school_nm='Rutgers' or abbreviation='Rutgers'));
insert into ranks (season,wk,rank,team_id) values(2007,2,16,(select team_id from teams where school_nm='Nebraska' or abbreviation='Nebraska'));
insert into ranks (season,wk,rank,team_id) values(2007,2,17,(select team_id from teams where school_nm='Auburn' or abbreviation='Auburn'));
insert into ranks (season,wk,rank,team_id) values(2007,2,18,(select team_id from teams where school_nm='Arkansas' or abbreviation='Arkansas'));
insert into ranks (season,wk,rank,team_id) values(2007,2,19,(select team_id from teams where school_nm='TCU' or abbreviation='TCU'));
insert into ranks (season,wk,rank,team_id) values(2007,2,20,(select team_id from teams where school_nm='Hawaii' or abbreviation='Hawaii'));
insert into ranks (season,wk,rank,team_id) values(2007,2,21,(select team_id from teams where school_nm='Georgia Tech' or abbreviation='Georgia Tech'));
insert into ranks (season,wk,rank,team_id) values(2007,2,22,(select team_id from teams where school_nm='Boise State' or abbreviation='Boise State'));
insert into ranks (season,wk,rank,team_id) values(2007,2,23,(select team_id from teams where school_nm='Texas A&M' or abbreviation='Texas A&M'));
insert into ranks (season,wk,rank,team_id) values(2007,2,24,(select team_id from teams where school_nm='Tennessee' or abbreviation='Tennessee'));
insert into ranks (season,wk,rank,team_id) values(2007,2,25,(select team_id from teams where school_nm='Clemson' or abbreviation='Clemson'));