delete from games;
delete from teams;
delete from conferences;

insert into conferences values (null,'ACC');
insert into conferences values (null,'Big 12');
insert into conferences values (null,'Big East');
insert into conferences values (null,'Big Sky');
insert into conferences values (null,'Big South');
insert into conferences values (null,'Big Ten');
insert into conferences values (null,'C-USA');
insert into conferences values (null,'CAA');
insert into conferences values (null,'Great West');
insert into conferences values (null,'Independent');
insert into conferences values (null,'Independent2');
insert into conferences values (null,'Ivy');
insert into conferences values (null,'MAC');
insert into conferences values (null,'MEAC');
insert into conferences values (null,'Missouri Valley');
insert into conferences values (null,'Mountain West');
insert into conferences values (null,'NEC');
insert into conferences values (null,'OVC');
insert into conferences values (null,'Pac-10');
insert into conferences values (null,'Patriot');
insert into conferences values (null,'Pioneer');
insert into conferences values (null,'SEC');
insert into conferences values (null,'Southern');
insert into conferences values (null,'Southland');
insert into conferences values (null,'Sun Belt');
insert into conferences values (null,'SWAC');
insert into conferences values (null,'WAC');

insert into teams values (null,'Boston College','Eagles','BC',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Clemson','Tigers','CLEM',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Duke','Blue Devils','DUKE',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Florida State','Seminoles','FL ST',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Georgia Tech','Yellow Jackets','GT',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Maryland','Terrapins','MARY',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Miami','Hurricanes','MIAMI',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'NC State','Wolfpack','NC ST',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'North Carolina','Tar Heels','NC ST',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Virginia','Cavaliers','VIRG',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Virginia Tech','Hokies','VT',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Wake Forest','Demon Deacons','WF',(select conference_id from conferences where conference_nm='ACC'));
insert into teams values (null,'Baylor','Bears','BAYLOR',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Colorado','Buffaloes','COL',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Iowa State','Cyclones','IOWAST',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Kansas','Jayhawks','KANSAS',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Kansas State','Wildcats','K ST',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Missouri','Tigers','MIZZU',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Nebraska','Cornhuskers','NEB',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Oklahoma','Sooners','OKLA',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Oklahoma State','Cowboys','OK ST',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Texas','Longhorns','TEXAS',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Texas A&M','Aggies','A&M',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Texas Tech','Red Raiders','TT',(select conference_id from conferences where conference_nm='Big 12'));
insert into teams values (null,'Cincinnati','Bearcats','CIN',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'Connecticut','Huskies','UCONN',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'Louisville','Cardinals','LVILLE',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'Pittsburgh','Panthers','PITT',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'Rutgers','Scarlet Knights','RUTG',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'South Florida','Bulls','USF',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'Syracuse','Orange','SYR',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'West Virginia','Mountaineers','WV',(select conference_id from conferences where conference_nm='Big East'));
insert into teams values (null,'Eastern Washington','Eagles','E WASH',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Idaho State','Bengals','IDAHO',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Montana','Grizzlies','MONT',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Montana State','Bobcats','MONTST',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Northern Arizona','Lumberjacks','N AZ',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Northern Colorado','Bears','N COL',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Portland State','Vikings','PORTLD',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Sacramento State','Hornets','SAC',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Weber State','Wildcats','WEBER',(select conference_id from conferences where conference_nm='Big Sky'));
insert into teams values (null,'Charleston Southern','Buccaneers','CHRLST',(select conference_id from conferences where conference_nm='Big South'));
insert into teams values (null,'Coastal Carolina','Chanticleers','CSTCAR',(select conference_id from conferences where conference_nm='Big South'));
insert into teams values (null,'Gardner-Webb','Runnin Bulldogs','GARWEB',(select conference_id from conferences where conference_nm='Big South'));
insert into teams values (null,'Liberty','Flames','LIBRTY',(select conference_id from conferences where conference_nm='Big South'));
insert into teams values (null,'Presbyterian','Blue Hose','PRESB',(select conference_id from conferences where conference_nm='Big South'));
insert into teams values (null,'Stony Brook','Seawolves','STONY',(select conference_id from conferences where conference_nm='Big South'));
insert into teams values (null,'VMI','Keydets','VMI',(select conference_id from conferences where conference_nm='Big South'));
insert into teams values (null,'Illinois','Fighting Illini','ILL',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Indiana','Hoosiers','IND',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Iowa','Hawkeyes','IOWA',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Michigan','Wolverines','MICH',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Michigan State','Spartans','MICHST',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Minnesota','Golden Gophers','MINN',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Northwestern','Wildcats','NW',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Ohio State','Buckeyes','OHIOST',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Penn State','Nittany Lions','PENNST',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Purdue','Boilermakers','PURDUE',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'Wisconsin','Badgers','WIS',(select conference_id from conferences where conference_nm='Big Ten'));
insert into teams values (null,'East Carolina','Pirates','ECU',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Houston','Cougars','HOUSTN',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Marshall','Thundering Herd','MARSHL',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Memphis','Tigers','MEMPHS',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Rice','Owls','RICE',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Southern Methodist','Mustangs','SMU',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Southern Miss','Golden Eagles','SOMISS',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Tulane','Green Wave','TULANE',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Tulsa','Golden Hurricane','TULSA',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'UAB','Blazers','UAB',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'UCF','Knights','UCF',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'UTEP','Miners','UTEP',(select conference_id from conferences where conference_nm='C-USA'));
insert into teams values (null,'Delaware','Fightin Blue Hens','DEL',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Hofstra','Pride','HOFSTR',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'James Madison','Dukes','JMAD',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Maine','Black Bears','MAINE',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Massachusetts','Minutemen','MASS',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'New Hampshire','Wildcats','NH',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Northeastern','Huskies','NOREAS',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Rhode Island','Rams','RI',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Richmond','Spiders','RICH',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Towson','Tigers','TOWSON',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Villanova','Wildcats','VILL',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'William & Mary','Tribe','W&M',(select conference_id from conferences where conference_nm='CAA'));
insert into teams values (null,'Cal Poly','Mustangs','CALPOL',(select conference_id from conferences where conference_nm='Great West'));
insert into teams values (null,'North Dakota','Fighting Sioux','ND',(select conference_id from conferences where conference_nm='Great West'));
insert into teams values (null,'South Dakota','Coyotes','SD',(select conference_id from conferences where conference_nm='Great West'));
insert into teams values (null,'Southern Utah','Thunderbirds','S UTAH',(select conference_id from conferences where conference_nm='Great West'));
insert into teams values (null,'California-Davis','Aggies','UC DAV',(select conference_id from conferences where conference_nm='Great West'));
insert into teams values (null,'Army','Black Knights','ARMY',(select conference_id from conferences where conference_nm='Independent'));
insert into teams values (null,'Navy','Midshipmen','NAVY',(select conference_id from conferences where conference_nm='Independent'));
insert into teams values (null,'Notre Dame','Fighting Irish','ND',(select conference_id from conferences where conference_nm='Independent'));
insert into teams values (null,'Western Kentucky','Hilltoppers','WK',(select conference_id from conferences where conference_nm='Independent'));
insert into teams values (null,'Iona','Gaels','IONA',(select conference_id from conferences where conference_nm='Independent2'));
insert into teams values (null,'Marist','Red Foxes','MARIST',(select conference_id from conferences where conference_nm='Independent2'));
insert into teams values (null,'North Carolina Central','Eagles','NC CNT',(select conference_id from conferences where conference_nm='Independent2'));
insert into teams values (null,'Savannah State','Tigers','SAVST',(select conference_id from conferences where conference_nm='Independent2'));
insert into teams values (null,'Brown','Bears','BROWN',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Columbia','Lions','COLUM',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Cornell','Big Red','CORNEL',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Dartmouth','Big Green','DART',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Harvard','Crimson','HARVRD',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Pennsylvania','Quakers','PENN',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Princeton','Tigers','PRINCE',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Yale','Bulldogs','YALE',(select conference_id from conferences where conference_nm='Ivy'));
insert into teams values (null,'Akron','Zips','AKRON',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Ball State','Cardinals','BALLST',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Bowling Green','Falcons','BG',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Buffalo','Bulls','BUFF',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Central Michigan','Chippewas','CM',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Eastern Michigan','Eagles','EM',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Kent State','Golden Flashes','KENT',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Miami (OH)','RedHawks','MI OH',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Northern Illinois','Huskies','NI',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Ohio','Bobcats','OHIO',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Temple','Owls','TEMPLE',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Toledo','Rockets','TOLEDO',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Western Michigan','Broncos','WM',(select conference_id from conferences where conference_nm='MAC'));
insert into teams values (null,'Bethune-Cookman','Wildcats','BETHUN',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Delaware State','Hornets','DELST',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Florida A&M','Rattlers','FLAA&M',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Hampton','Pirates','HAMPTN',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Howard','Bison','HOWARD',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Morgan State','Bears','MORGAN',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Norfolk State','Spartans','NORFOL',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'North Carolina A&T','Aggies','NC A&T',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'South Carolina State','Bulldogs','SC ST',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Winston-Salem State','Rams','W-S ST',(select conference_id from conferences where conference_nm='MEAC'));
insert into teams values (null,'Illinois State','Redbirds','ILL ST',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'Indiana State','Sycamores','IND ST',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'Missouri State','Bears','MIZZST',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'North Dakota State','Bison','ND ST',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'Northern Iowa','Panthers','N IOWA',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'South Dakota State','Jackrabbits','SD ST',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'Southern Illinois','Salukis','S ILL',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'Western Illinois','Leathernecks','W ILL',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'Youngstown State','Penguins','YTOWN',(select conference_id from conferences where conference_nm='Missouri Valley'));
insert into teams values (null,'Air Force','Falcons','AF',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'Brigham Young','Cougars','BYU',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'Colorado State','Rams','COL ST',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'New Mexico','Lobos','NM',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'San Diego State','Aztecs','SD ST',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'TCU','Horned Frogs','TCU',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'UNLV','Rebels','UNLV',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'Utah','Utes','UTAH',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'Wyoming','Cowboys','WYO',(select conference_id from conferences where conference_nm='Mountain West'));
insert into teams values (null,'Albany','Great Danes','ALBANY',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Bryant','Bulldogs','BRYANT',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Central Connecticut','Blue Devils','C CONN',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Duquesne','Dukes','DUQ',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Monmouth','Hawks','MONMTH',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Robert Morris','Colonials','ROBMOR',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Sacred Heart','Pioneers','SACHRT',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Saint Francis','Red Flash','STFRAN',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Wagner','Seahawks','WAGNER',(select conference_id from conferences where conference_nm='NEC'));
insert into teams values (null,'Austin Peay','Governors','AUSTIN',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Eastern Illinois','Panthers','E ILL',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Eastern Kentucky','Colonels','E KENT',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Jacksonville State','Gamecocks','JVILST',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Murray State','Racers','MURRAY',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Southeast Missouri State','Redhawks','SEMIZZ',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Tennessee State','Tigers','TENNST',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Tennessee Tech','Golden Eagles','TENTEK',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Tennessee-Martin','Skyhawks','TENMAR',(select conference_id from conferences where conference_nm='OVC'));
insert into teams values (null,'Arizona','Wildcats','AZ',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'Arizona State','Sun Devils','AZ ST',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'California','Golden Bears','CAL',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'Oregon','Ducks','OREGON',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'Oregon State','Beavers','ORE ST',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'Stanford','Cardinal','STAN',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'UCLA','Bruins','UCLA',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'USC','Trojans','USC',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'Washington','Huskies','WASH',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'Washington State','Cougars','WASHST',(select conference_id from conferences where conference_nm='Pac-10'));
insert into teams values (null,'Bucknell','Bison','BUCKNL',(select conference_id from conferences where conference_nm='Patriot'));
insert into teams values (null,'Colgate','Raiders','COLGAT',(select conference_id from conferences where conference_nm='Patriot'));
insert into teams values (null,'Fordham','Rams','FORDHM',(select conference_id from conferences where conference_nm='Patriot'));
insert into teams values (null,'Georgetown','Hoyas','GTOWN',(select conference_id from conferences where conference_nm='Patriot'));
insert into teams values (null,'Holy Cross','Crusaders','HOLYX',(select conference_id from conferences where conference_nm='Patriot'));
insert into teams values (null,'Lafayette','Leopards','LAF',(select conference_id from conferences where conference_nm='Patriot'));
insert into teams values (null,'Lehigh','Mountain Hawks','LEHIGH',(select conference_id from conferences where conference_nm='Patriot'));
insert into teams values (null,'Butler','Bulldogs','BUTLER',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Campbell','Fighting Camels','CAMPBL',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Davidson','Wildcats','DAVID',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Dayton','Flyers','DAYTON',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Drake','Bulldogs','DRAKE',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Jacksonville','Dolphins','JVILLE',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Morehead State','Eagles','MORHED',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'San Diego','Toreros','SANDIE',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Valparaiso','Crusaders','VALP',(select conference_id from conferences where conference_nm='Pioneer'));
insert into teams values (null,'Alabama','Crimson Tide','BAMA',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Arkansas','Razorbacks','ARK',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Auburn','Tigers','AUBURN',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Florida','Gators','FLA',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Georgia','Bulldogs','GEO',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Kentucky','Wildcats','KENTUK',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'LSU','Tigers','LSU',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Mississippi State','Bulldogs','MISSST',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Mississippi','Rebels','OLE MS',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'South Carolina','Gamecocks','SC',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Tennessee','Volunteers','TENN',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Vanderbilt','Commodores','VAND',(select conference_id from conferences where conference_nm='SEC'));
insert into teams values (null,'Appalachian State','Mountaineers','APP ST',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Chattanooga','Mocs','CHATT',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Elon','Phoenix','ELON',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Furman','Paladins','FURMAN',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Georgia Southern','Eagles','GSOUTH',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Citadel','Bulldogs','CITDEL',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Western Carolina','Catamounts','W CAR',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Wofford','Terriers','WOFFRD',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Samford','Bulldogs','SAMFRD',(select conference_id from conferences where conference_nm='Southern'));
insert into teams values (null,'Central Arkansas','Bears','C ARK',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'McNeese State','Cowboys','MCNEES',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'Nicholls State','Colonels','NICHST',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'Northwestern State','Demons','NW ST',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'Sam Houston State','Bearkats','SAMHOU',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'Southeastern Louisiana','Lions','SE LOU',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'Stephen F. Austin','Lumberjacks','SFAUST',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'Texas State','Bobcats','TEX ST',(select conference_id from conferences where conference_nm='Southland'));
insert into teams values (null,'Arkansas State','Red Wolves','ARK ST',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'FIU','Golden Panthers','FIU',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'Florida Atlantic','Owls','FAU',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'Louisiana-Lafayette','Ragin Cajuns','LL',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'Louisiana-Monroe','Warhawks','LM',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'Middle Tennessee','Blue Raiders','MT',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'North Texas','Mean Green','NT',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'Troy','Trojans','TROY',(select conference_id from conferences where conference_nm='Sun Belt'));
insert into teams values (null,'Alabama A&M','Bulldogs','A A&M',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Alabama State','Hornets','AL ST',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Alcorn State','Braves','ALCORN',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Arkansas-Pine Bluff','Golden Lions','AR-PB',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Grambling State','Tigers','GRAMB',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Jackson State','Tigers','JACKSN',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Mississippi Valley State','Delta Devils','MVST',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Prairie View A&M','Panthers','PV A&M',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Southern','Jaguars','SOTHRN',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Texas Southern','Tigers','TEX S',(select conference_id from conferences where conference_nm='SWAC'));
insert into teams values (null,'Boise State','Broncos','BOISE',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'Fresno State','Bulldogs','FRESNO',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'Hawaii','Warriors','HAWAII',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'Idaho','Vandals','IDAHO',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'Louisiana Tech','Bulldogs','LT',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'Nevada','Wolf Pack','NEVADA',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'New Mexico State','Aggies','NM ST',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'San Jose State','Spartans','SJ ST',(select conference_id from conferences where conference_nm='WAC'));
insert into teams values (null,'Utah State','Aggies','UTAHST',(select conference_id from conferences where conference_nm='WAC'));

